//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvensiaWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryDescription
    {
        public int ID { get; set; }
        public int ProductCategoryID { get; set; }
        public string CategoryDescription1 { get; set; }
        public string CategoryImageName { get; set; }
        public string Culture { get; set; }
        public System.Guid rowguid { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
