//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvensiaWebShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vProductAndDescripttionExtendedENOnly
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string ProductModel { get; set; }
        public string Culture { get; set; }
        public string Description { get; set; }
        public string ProductNumber { get; set; }
        public string Color { get; set; }
        public decimal ListPrice { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public byte[] ThumbNailPhoto { get; set; }
        public int ProductModelID { get; set; }
        public string DiscountLabel { get; set; }
        public Nullable<double> DiscountProcent { get; set; }
        public Nullable<double> DiscountValue { get; set; }
        public Nullable<bool> DiscountActive { get; set; }
        public string ThumbnailPhotoFileName { get; set; }
        public Nullable<bool> Primary { get; set; }
        public string LargePhotoFileName { get; set; }
    }
}
